# -*- coding: utf-8 -*-
"""DiabetesMLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14t3x8M7SU-4TSxf5ZnVFOfdxIRUXKJyK

# Importing Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

"""# Load Dataset"""

diabetes_dataset = pd.read_csv('/content/diabetes.csv')
diabetes_dataset

diabetes_dataset.head()

diabetes_dataset.tail()

diabetes_dataset.info()

diabetes_dataset.describe()

diabetes_dataset.shape

diabetes_dataset.isnull().sum()

diabetes_dataset.nunique()

diabetes_dataset['Outcome'].value_counts()

diabetes_dataset.groupby('Outcome').mean()

X = diabetes_dataset.drop(columns='Outcome', axis=1)
Y = diabetes_dataset['Outcome']

X

Y

scaler = StandardScaler()
scaler.fit(X)

Standardized_data = scaler.transform(X)
Standardized_data

X = Standardized_data
Y = diabetes_dataset['Outcome']

X

Y

"""# Train Test Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

classifier = svm.SVC(kernel='linear')
classifier.fit(X_train,Y_train)

X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy of training data: ',training_data_accuracy)

X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy of testing data: ',testing_data_accuracy)

"""# Predictive System"""

input_data = np.array([1,85,66,29,0,26.6,0.351,31])

input_data_reshaped = input_data.reshape(1,-1)

std_data = scaler.transform(input_data_reshaped)


prediction = classifier.predict(std_data)
print(prediction)

if prediction[0] == 0:
  print("Low risk of Diabetes")
else:
  print("High risk of Diabetes")

import pickle

filename = 'Diabetes_model.sav'
with open(filename, 'wb') as file:
    pickle.dump(classifier, file)

loaded_model = pickle.load(open('Diabetes_model.sav','rb'))

with open("scaler.sav", "wb") as f:
    pickle.dump(scaler, f)