# -*- coding: utf-8 -*-
"""HeartMLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzXMagNtvrdStnjoQ07ojU59EKssdVEG

# Importing Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

"""# Read Data and Preprocess"""

heart_data = pd.read_csv('/content/heart.csv')
heart_data

heart_data.head()

heart_data.tail()

heart_data.describe()

heart_data.info()

heart_data.shape

heart_data.isnull().sum()

heart_data.nunique()

corr = heart_data.corr()
corr.style.background_gradient(cmap='coolwarm')

sns.histplot(heart_data['age'], bins=20, kde=True, color='blue')
plt.title("Age Distribution")
plt.show()

sns.countplot(x=heart_data['target'], palette="Set1")
plt.title("Distribution of Heart Disease")
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(heart_data.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

heart_data['target'].value_counts()

X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

print(X)

print(Y)

"""# Train Test Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

"""# Logistic Regression"""

model = LogisticRegression()
model.fit(X_train, Y_train)

"""# Model Evaluation"""

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy of training data: ',training_data_accuracy)

X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy of testing data: ',testing_data_accuracy)

"""# Building a prediction system"""

input_data = np.array([71, 0, 0, 112, 149, 0, 1, 125, 0, 1.6, 1, 0, 2])

input_data_reshaped = input_data.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)

if prediction[0] == 0:
  print("Low risk of Heart Disease")
else:
  print("High risk of Heart Disease")

import pickle

filename = 'HeartDisease_model.sav'
with open(filename, 'wb') as file:
    pickle.dump(model, file)

loaded_model = pickle.load(open('HeartDisease_model.sav','rb'))